version: '3'
services:
  app:
    container_name: "app"
    build: "./docker/go-debug"
    volumes:
      - ".:${GO_PROJECT_DIR}"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/app"
    ports:
      - "8080:8080"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"